### ISSUE TITLE
Add support for Timestamp9 data type without time zone information

### ISSUE THREAD

**Issue by higuoxing** [fvannee/timestamp9#9]
Hi, @fvannee 

Currently, timestamp9 only recognize timestamp with time zone information `'y-m-d h:m:s.ns +tz'`,  while Postgres supports both `timestamp` and `timestamptz` data types. What about making the current timestamp9 data type to `timestamp9tz` and introduce a new data type `timestamp9` (timestamp9 without time zone information)? What do you think of it? I think I can help implement it.

**Comment by fvannee** [comment]
I don't think renaming of the existing type is going to happen. I also don't think the whole concept of `timestamp` is very useful, because it's stored exactly the same as a `timestamptz`: it's just converted to/from UTC on write/read.
Is your problem that you actually want a `timestamp`-like object, or do you just want to be able to provide a nanosecond timestamp text to timestamp9 conversion where you don't need to specify a timezone? For example, the following works for timestamptz: `select '2023-01-01 10:00:00.100001'::timestamptz`. Postgres assumes the local timezone. Timestamp9 does no such thing if you specify a nanosecond precision timestamp. This fails: `select '2023-01-01 10:00:00.100000001'::timestamp9` This is something that could be implemented in the text->timestamp9 conversion. Would that solve your problem?

**Comment by higuoxing** [comment]
Yes, I think teaching timestamp9 accept `select '2023-01-01 10:00:00.100000001'::timestamp9` makes sense. I'll give it a try.
